const SET_PRODUCTS = "PRODUCT SET_PRODUCTS";
const SET_PRODUCT_DETAIL = "PRODUCT SET_PRODUCT_DETAIL";
// const GET_CATEGORY_PRODUCTS = "PRODUCT GET_CATEGORY_PRODUCTS"

export { SET_PRODUCTS, SET_PRODUCT_DETAIL };
